### ISSUE TITLE
Add the cross-chain monitoring capability 

### ISSUE THREAD

**Issue by mojtaba-eshghie** [mojtaba-eshghie/HighGuard#116]

**Comment by mojtaba-eshghie** [comment]
Hi @hansstammler 

With the following command: 
`node CI/setup-cross-chain.js`

I get the following execution+error logs:
```bash
2024-05-25 18:29:59 [debug]: Starting Anvil...
2024-05-25 18:30:00 [debug]: Finished running Anvil...
2024-05-25 18:30:00 [debug]: Starting Avalanche...
2024-05-25 18:30:00 [debug]: Starting to setup avalance index... (setupEnv)
2024-05-25 18:30:00 [debug]: Exectuing command: "avalanche network clean"
2024-05-25 18:30:01 [debug]: Executing command: "avalanche subnet list"
2024-05-25 18:30:01 [debug]: subnetList: +--------------------+--------------------+-----------+---------------------------------------------------+------------+------------+-----------+
|       SUBNET       |       CHAIN        |  CHAINID  |                       VMID                        |    TYPE    | VM VERSION | FROM REPO |
+--------------------+--------------------+-----------+---------------------------------------------------+------------+------------+-----------+
| highguardAvalanche | highguardAvalanche | 348753265 | nz4LoyaTay1wrnyVUnbNyKmuyK8qxyPi6Hsox2B2DVsZVEuPZ | Subnet-EVM | v0.6.3     | false     |
+--------------------+--------------------+-----------+---------------------------------------------------+------------+------------+-----------+

Deploying [highguardAvalanche] to Local Network

Backend controller started, pid: 61381, output at: /Users/mojtabaeshghie/.avalanche-cli/runs/server_20240525_183002/avalanche-cli-backend.log

2024-05-25 18:30:03 [debug]: data: 

Booting Network. Wait until healthy...

Node logs directory: /Users/mojtabaeshghie/.avalanche-cli/runs/network_20240525_183003/node<i>/logs

Network ready to use.debug]: data: 

2024-05-25 18:30:14 [debug]: data: 

Deploying Blockchain. Wait until network acknowledges...

2024-05-25 18:30:20 [debug]: data: 

Teleporter Messenger successfully deployed to c-chain (0x253b2784c75e510dD0fF1da844684a1aC0aa5fcf)

Teleporter Registry successfully deployed to c-chain (0x17aB05351fC94a1a67Bf3f56DdbB941aE6c63E25)

2024-05-25 18:30:26 [debug]: data: 

Teleporter Messenger successfully deployed to highguardAvalanche (0x253b2784c75e510dD0fF1da844684a1aC0aa5fcf)

Teleporter Registry successfully deployed to highguardAvalanche (0x42B0fDB391549308C1A60F1fa8d4DFC46A4B6Bc8)

2024-05-25 18:30:32 [debug]: data: 

Blockchain ready to use. Local network node endpoints:
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| NODE  |         VM         |                                        URL                                         |                      ALIAS URL                      |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| node1 | highguardAvalanche | http://127.0.0.1:9650/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc | http://127.0.0.1:9650/ext/bc/highguardAvalanche/rpc |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| node2 | highguardAvalanche | http://127.0.0.1:9652/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc | http://127.0.0.1:9652/ext/bc/highguardAvalanche/rpc |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| node3 | highguardAvalanche | http://127.0.0.1:9654/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc | http://127.0.0.1:9654/ext/bc/highguardAvalanche/rpc |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| node4 | highguardAvalanche | http://127.0.0.1:9656/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc | http://127.0.0.1:9656/ext/bc/highguardAvalanche/rpc |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+
| node5 | highguardAvalanche | http://127.0.0.1:9658/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc | http://127.0.0.1:9658/ext/bc/highguardAvalanche/rpc |
+-------+--------------------+------------------------------------------------------------------------------------+-----------------------------------------------------+


Browser Extension connection details (any node URL from above works):
RPC URL:           http://127.0.0.1:9650/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc
Funded address:    0x5a1f454572387D49E9761194c36F2878Ffeb95Fa with 600
Network name:      highguardAvalanche
Chain ID:          348753265
Currency Symbol:   AVAX

2024-05-25 18:30:32 [debug]: Finished running Avalanche
2024-05-25 18:30:32 [debug]: Web3 A: 127.0.0.1:3094
2024-05-25 18:30:32 [debug]: Web3 B: http://127.0.0.1:9650/ext/bc/adahcCCfjGQq7dibQP7yD6gCp9XryBP488xqKDE4Z4CN8kbDF/rpc
2024-05-25 18:30:32 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:34 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:35 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:35 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:36 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:37 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js

contractFileName: Router, 
contractIdentifier: Router
2024-05-25 18:30:38 [debug]:  exactVersion: soljson-v0.8.20+commit.a1b79de6.js
2024-05-25 18:30:39 [debug]: Found the activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
2024-05-25 18:30:39 [debug]: Found the activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
2024-05-25 18:30:39 [info]: Monitor A is now running.
2024-05-25 18:30:39 [info]: Monitor B is now running.
Bridge deployed
2024-05-25 18:30:39 [debug]: Executing sequence
2024-05-25 18:30:39 [debug]: Response: [object Object]
2024-05-25 18:30:39 [debug]: Response: [object Object]
2024-05-25 18:30:39 [debug]: Monitor B is initialized...
2024-05-25 18:30:39 [info]: Monitor B is now running.
Bridge deployed
2024-05-25 18:30:39 [debug]: Executing sequence
2024-05-25 18:30:39 [debug]: The simulation id for the monitor: 2012159
2024-05-25 18:30:39 [debug]: Monitor A is initialized...
2024-05-25 18:30:39 [info]: Monitor A is now running.
Bridge deployed
2024-05-25 18:30:39 [debug]: Executing sequence
2024-05-25 18:30:39 [debug]: The simulation id for the monitor: 2012159
0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
Event on chain: B
Deposit: ADD:B.AVAX:_
0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
2024-05-25 18:30:43 [info]: our method is: [object Object]
2024-05-25 18:30:43 [debug]: Translating and finding this method: deposit
key: 0, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: 1, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: 2, value: 0
this.modelFunctionParams: null
key: 3, value: ADD:B.AVAX:_
this.modelFunctionParams: null
key: __length__, value: 4
this.modelFunctionParams: null
key: vault, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: asset, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: amount, value: 0
this.modelFunctionParams: null
key: memo, value: ADD:B.AVAX:_
this.modelFunctionParams: null
2024-05-25 18:30:43 [debug]: activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
 method.name: deposit
2024-05-25 18:30:43 [info]: dcrActivities: null
2024-05-25 18:30:43 [info]: LINE 94 monitor
2024-05-25 18:30:43 [error]: LINE 121 monitor
2024-05-25 18:30:43 [info]: our method is: [object Object]
2024-05-25 18:30:43 [debug]: Translating and finding this method: deposit
key: 0, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: 1, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: 2, value: 0
this.modelFunctionParams: null
key: 3, value: ADD:B.AVAX:_
this.modelFunctionParams: null
key: __length__, value: 4
this.modelFunctionParams: null
key: vault, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: asset, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: amount, value: 0
this.modelFunctionParams: null
key: memo, value: ADD:B.AVAX:_
this.modelFunctionParams: null
2024-05-25 18:30:43 [debug]: activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
 method.name: deposit
2024-05-25 18:30:43 [info]: dcrActivities: null
2024-05-25 18:30:43 [info]: LINE 94 monitor
2024-05-25 18:30:43 [error]: LINE 121 monitor
2024-05-25 18:30:43 [debug]: We received a new transaction: {"blockHash":"0xac08eaecea81d808ed004f1760c0e24fb80b0cf42f0648df1b2641047facb1c2","blockNumber":8,"from":"0x6e79ddAf3f067026238BB842dd615c6cE182564e","gas":300000,"gasPrice":"27500000000","maxFeePerGas":"52500000000","maxPriorityFeePerGas":"2500000000","hash":"0x07916c8f5e099a5fd1137da0a8051179f7843367dd93fae14f165e8a5ca6f68f","input":"0x1fece7b400000000000000000000000082108623783343cd55a63570d4673d458a865610000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000c4144443a422e415641583a5f0000000000000000000000000000000000000000","nonce":3,"to":"0x2e8E1CE776ae084bA7b7D8439FEEeCf35b25cC84","transactionIndex":0,"value":"100000","type":2,"accessList":[],"chainId":"0x14c98d71","v":"0x0","r":"0xf304807098d4cb249f1ebb0479f0163d87cb620cfbeba2899c3f06e991e1f14f","s":"0x3f02fed0a98d70e98e84344bd6584cebdbdaac36702b9a2acbb1e1d9a622402","yParity":"0x0"}
2024-05-25 18:30:43 [info]: our method is: [object Object]
2024-05-25 18:30:43 [debug]: Translating and finding this method: deposit
key: 0, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: 1, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: 2, value: 0
this.modelFunctionParams: null
key: 3, value: ADD:B.AVAX:_
this.modelFunctionParams: null
key: __length__, value: 4
this.modelFunctionParams: null
key: vault, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: asset, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: amount, value: 0
this.modelFunctionParams: null
key: memo, value: ADD:B.AVAX:_
this.modelFunctionParams: null
2024-05-25 18:30:43 [debug]: activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
 method.name: deposit
2024-05-25 18:30:43 [info]: dcrActivities: null
2024-05-25 18:30:43 [info]: LINE 94 monitor
2024-05-25 18:30:43 [error]: LINE 121 monitor
2024-05-25 18:30:43 [info]: our method is: [object Object]
2024-05-25 18:30:43 [debug]: Translating and finding this method: deposit
key: 0, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: 1, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: 2, value: 0
this.modelFunctionParams: null
key: 3, value: ADD:B.AVAX:_
this.modelFunctionParams: null
key: __length__, value: 4
this.modelFunctionParams: null
key: vault, value: 0x82108623783343cD55a63570d4673D458A865610
this.modelFunctionParams: null
key: asset, value: 0x0000000000000000000000000000000000000000
this.modelFunctionParams: null
key: amount, value: 0
this.modelFunctionParams: null
key: memo, value: ADD:B.AVAX:_
this.modelFunctionParams: null
2024-05-25 18:30:43 [debug]: activities: ["avax_deposit","avax_payout","eth_deposit","eth_payout","Activity9","Activity7"]
 method.name: deposit
2024-05-25 18:30:43 [info]: dcrActivities: null
2024-05-25 18:30:43 [info]: LINE 94 monitor
2024-05-25 18:30:43 [error]: LINE 121 monitor
2024-05-25 18:30:43 [debug]: We received a new transaction: {"blockHash":"0xac08eaecea81d808ed004f1760c0e24fb80b0cf42f0648df1b2641047facb1c2","blockNumber":8,"from":"0x6e79ddAf3f067026238BB842dd615c6cE182564e","gas":300000,"gasPrice":"27500000000","maxFeePerGas":"52500000000","maxPriorityFeePerGas":"2500000000","hash":"0x07916c8f5e099a5fd1137da0a8051179f7843367dd93fae14f165e8a5ca6f68f","input":"0x1fece7b400000000000000000000000082108623783343cd55a63570d4673d458a865610000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000c4144443a422e415641583a5f0000000000000000000000000000000000000000","nonce":3,"to":"0x2e8E1CE776ae084bA7b7D8439FEEeCf35b25cC84","transactionIndex":0,"value":"100000","type":2,"accessList":[],"chainId":"0x14c98d71","v":"0x0","r":"0xf304807098d4cb249f1ebb0479f0163d87cb620cfbeba2899c3f06e991e1f14f","s":"0x3f02fed0a98d70e98e84344bd6584cebdbdaac36702b9a2acbb1e1d9a622402","yParity":"0x0"}
100000
/Users/mojtabaeshghie/projects/highguard/node_modules/solc/soljson.js:133
    process["on"]("unhandledRejection", function (reason) { throw reason; });
                                                            ^

Error: Returned error: already known
    at Object.ErrorResponse (/Users/mojtabaeshghie/projects/highguard/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at Object.callback (/Users/mojtabaeshghie/projects/highguard/node_modules/web3-core-requestmanager/lib/index.js:300:36)
    at /Users/mojtabaeshghie/projects/highguard/node_modules/web3-providers-ws/lib/index.js:115:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/Users/mojtabaeshghie/projects/highguard/node_modules/web3-providers-ws/lib/index.js:103:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/mojtabaeshghie/projects/highguard/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/Users/mojtabaeshghie/projects/highguard/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/mojtabaeshghie/projects/highguard/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.processFrame (/Users/mojtabaeshghie/projects/highguard/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/mojtabaeshghie/projects/highguard/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  data: null
}

```
