### ISSUE TITLE
Using HighGuard in Client-Server Mode and Clawk Standalone CLI Monitor

### ISSUE THREAD

**Issue by Puisque** [mojtaba-eshghie/HighGuard#79]
Hi @mojtaba-eshghie @hansstammler,
Thanks for helping and resolving the previous bug. I really appreciate your effort. I could finally get some result on my terminal. 
However, apart from directly running the "monitor/monitor.test.js " file, I was also trying to follow the README file and when I was trying to use "HighGuard in Client-Server Mode" i got this for the server part:
```
liu@n150-p125 HighGuard % cd server 
liu@n150-p125 server % ls
config		index.js	index.test.js	monitor		routes.js
liu@n150-p125 server % npm start

> dragonclaw@1.0.0 start
> nodemon server/index.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/index.js`
/Users/liu/HighGuard/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/Users/liu/HighGuard/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/Users/liu/HighGuard/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/liu/HighGuard/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.11.1
[nodemon] app crashed - waiting for file changes before starting...

```
and the following for the client:
```
liu@n150-p125 HighGuard % cd client 
liu@n150-p125 client % ls
README.md		package-lock.json	package.json		public			src
liu@n150-p125 client % npm start

> client@0.1.0 start
> react-scripts --openssl-legacy-provider start

sh: react-scripts: command not found
liu@n150-p125 client % 
```
Am I on the right track, not sure how to proceed... Need some help.

**Comment by Puisque** [comment]
update: talked to the author and I think some functionalities on the readme file changed :)

**Comment by mojtaba-eshghie** [comment]
> update: talked to the author and I think some functionalities on the readme file changed :)

Good luck with the rest!
